### ISSUE TITLE
HEAD method handler doesn't set 'Cache-Control' header in the response.

### ISSUE THREAD

**Issue by iarenaza** [akvo/resumed#3]
According to the tus 1.0.0 specification, the HEAD method (https://tus.io/protocols/resumable-upload.html#head) states that:

> The Server MUST prevent the client and/or proxies from caching the response by adding the Cache-Control: no-store header to the response.

But the code currently only sets the "Upload-Offset", "Upload-Length" and "Upload-Metadata" headers if the uploading file is found, or none if not.

**Comment by iperdomo** [comment]
@iarenaza you can update to released version to get the changes:

    [org.akvo/resumed "1.20.4ec0c35aff0cd3480b4bcade222c8fffefb4cc47"]

**Comment by iarenaza** [comment]
@iperdomo My reading of the spec is that the response to the HEAD request *always* needs to include the "Cache-Control" header, both when it returns 2xx and 4xx responses (the text quoted from the spec above doesn't qualify the type of response it applies to, so it should apply to all of them, shouldn't it?)

**Comment by iperdomo** [comment]
@iarenaza you're right

**Comment by iperdomo** [comment]
@iarenaza done

     [org.akvo/resumed "1.24.73c9ae0284874a326998e2bc5f99784e4aefa61e"]

Thanks for the bug report
