### ISSUE TITLE
`get-location` does not honor Host http header

### ISSUE THREAD

**Issue by iperdomo** [akvo/resumed#8]
We try to build a correct location after a `POST` request to start the `PATCH` process. If you're running the app server behind a reverse proxy (e.g. nginx) there are some complexities regarding how to proper build the correct `Location:` for the `PATCH` requests.

Depending of the browser `Origin` or `Host` requests are sent (e.g. Firefox doesn't send the `Origin` one)

We need to take into account the presence or not of:
* `X-Forwarded-Host`
* `X-Forwarded-Proto`
* `Origin`
* `Host` (it may include port, e.g. `host:port`)
* Fallback to `:server-name`, `:server-port` and `:scheme`

As of released version `1.27.7406c5e5be3ccd6d9e1f99d29f05ab1251682de7` the visible problem in a local development setup was that the server was returning the wrong server port and not the one present in `Host` header.

**Comment by iperdomo** [comment]
With the current state of the code we're handling the `Origin` header wrong

**Comment by kardan** [comment]
Closed by https://github.com/akvo/resumed/pull/10
